// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwA_yHMXyj8P--Z85mImSvUeEp-X3gkCE',
    appId: '1:1095829830280:web:9d7e5d42cb7c515dfc3d3d',
    messagingSenderId: '1095829830280',
    projectId: 'supa_flutter-9674e',
    authDomain: 'supa_flutter-9674e.firebaseapp.com',
    storageBucket: 'supa_flutter-9674e.firebasestorage.app',
    measurementId: 'G-2490YG9F1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARXd-3XHeWGRlDk9n3UUagSFjmO2uHWEk',
    appId: '1:1095829830280:android:c340bf625a2b41b7fc3d3d',
    messagingSenderId: '1095829830280',
    projectId: 'supa_flutter-9674e',
    storageBucket: 'supa_flutter-9674e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMpnI1aob262KpH5Bh5BG63IYA3GabQ9o',
    appId: '1:1095829830280:ios:54b82f23c7a6c2cafc3d3d',
    messagingSenderId: '1095829830280',
    projectId: 'supa_flutter-9674e',
    storageBucket: 'supa_flutter-9674e.firebasestorage.app',
    iosBundleId: 'com.supa_flutter.app',
  );

}
